[package]
name = "osam_plus"
version = "0.2.0-pre.1"
rust-version = "1.89"
edition = "2021"
repository = "https://github.com/sage-p1/rust_osam_plus.git"
description = "An implementation of Oblivious SAM."
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["osam_plus", "oblivious", "cryptography"]
categories = ["cryptography"]


[dependencies]
bit_reverse = "0.1.8"
subtle = "2"
rand = "0.8"
log = "0.4"
thiserror = "1"
aes-gcm = "0.11.0"
cipher = "0.5"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rustyline = "14"
paste = "1"
static_assertions = "1"
simplelog = "0.12"


[[bench]]
name = "benchmark"
harness = false
