// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// This source code is dual-licensed under either the MIT license found in the
// LICENSE-MIT file in the root directory of this source tree or the Apache
// License, Version 2.0 found in the LICENSE-APACHE file in the root directory
// of this source tree. You may select, at your option, one of the above-listed licenses.

//! An implementation of Oblivious SAM+ (OSAM+).
//!
//! ⚠️ **Warning**: This implementation has not been audited. Use at your own risk!
//!
//! # Overview
//!
//! This crate implements an oblivious SAM+ protocol (OSAM+).
//! OSAM+ supports three operations:
//!
//! * `addr <- Alloc()` generates a fresh address that has not been allocated before.
//!
//! * `Write(addr, val)` writes the given value to its associated address.
//!   Addresses can be overwritten several times.
//!   The given address must be produced by `Alloc()`.
//!
//! * `val <- Read(addr)` reads and returns the value associated with the given address.
//!   Addresses can only be read once.
//!   The given address must be produced by `Alloc()`.
//!   Reading an address that was allocated but not written is a valid operation.
//!
//! # Literature
//!
//! This crate implements the Path OSAM+ protocol and is derived from
//! [Facebook's Path ORAM](https://github.com/facebook/oram) implementation.
//! See [Concrete OSAM](https://eprint.iacr.org/2026/451.pdf) for an introduction
//! to the SAM+ and Path OSAM+ implementation. This work is adapted from the
//! [OSAM Model](https://eprint.iacr.org/2024/1029.pdf).
//! Facebook's original oblivious client data structures are based on the
//! [Oblix paper](https://people.eecs.berkeley.edu/~raluca/oblix.pdf). See the
//! [Path ORAM retrospective paper](http://elaineshi.com/docs/pathoram-retro.pdf)
//! for a high-level introduction to Path ORAM.
//!
//! # Design Specifications
//!
//! **Addresses**
//!
//! In this implementation of Path OSAM+, addresses consist of a tuple `(identifier, position)`.
//! An identifier is uniquely given by an increasing counter distinguish each block.
//! A position is a uniformly random leaf bucket a block is assigned to.
//!
//! **Correctness**
//!
//! For correctness, the client must respect the SAM+ rules:
//! * Valid addresses must be generated by `Alloc()`.
//! * Addresses can be read at most once.
//! * Addresses can be written many times. Stale versions of blocks are deleted by a `Merge()` function.
//!
//! There is no mechanism to enforce these rules.
//! It is up to the client to follow them correctly.
//!
//! **Eviction**
//!
//! In [Facebook's Path ORAM](https://github.com/facebook/oram), the path that was downloaded in a read
//! or write is always the path that is evicted.
//! We support two eviction strategies:
//! * [reverse-lexicographic eviction](https://eprint.iacr.org/2013/239.pdf), which deterministically
//!   and routinely evicts buckets.
//! * random eviction.
//!
//! When calling a function that evicts blocks to the server, use the boolean `ordered_evict` toggle between
//! reverse-lexicographic eviction and random eviction.
//!
//! **Encryption**
//!
//! [Facebook's Path ORAM](https://github.com/facebook/oram) also assumes the ORAM is being run in the
//! secure enclave setting and does not perform encryption on-write.
//! We do not maintain this assumption and allow for toggling between encrypted and plaintext backends for Path OSAM+.
//! This can be toggled with the boolean `is_encrypted` when initializing a Path OSAM+.
//!
//! **Local Operations**
//!
//! When calling `Write()` or `Read()`, there is one round-trip of interaction between the client and server.
//! In the SAM+ setting, we expect the client to be performing significantly more writes than reads.
//! To save on time, we introduce two functions two local functions that do not interact with the server:
//! * `LocalWrite(addr, val)` writes value to its associated address.
//!   Keeps the resulting block in the stash without evicting to the server.
//! * `LocalBatchWrite([(addr, val)])` writes a series of values to their associated addresses.
//!   Keeps the resulting block in the stash without evicting to the server.
//!
//! **Evicting Multiple Paths**
//!
//! Traditionally, Path ORAM/Path OSAM/Path OSAM+ handle single paths at a time.
//! We modify Path OSAM+ to store a constant `P`, for path count.
//! Rather than only evicting single paths at a time, we allow `P` paths to be evicted at once.
//! This eliminates stale versions of blocks at a faster pace.
//! The stash is allowed to hold more data to handle `P` paths simultaneously.
//! `Read()` and `Write()` still evict one path at a time, so the function:
//! * `val <- ReadMultiPaths()` reads and returns the value associated with the given address while evicting `P` paths.
//!
//! **Miscellaneous**
//!
//! There are some miscellaneous functions that:
//! * evict one or `P` paths to the server without reading an address.
//! * return the number of times a certain operation was done.
//! * compute the variance and standard deviation on stash occupancy (number of real blocks in the stash).
//!
//! # Example
//!
//! The below example reads a database from memory into a Path OSAM+, thus permitting secret-dependent accesses.
//!
//! ```
//! use osam_plus::{
//!     DEFAULT_BLOCKS_PER_BUCKET, DEFAULT_PATH_COUNT, DEFAULT_STASH_OVERFLOW_SIZE,
//!     BlockSize, BlockValue, Identifier, OsamPlus, OsamPlusError, PathOsamPlus, TreeIndex,
//! };
//! use rand::{rngs::OsRng, Rng};
//!
//! // Declare constants.
//! const BLOCK_SIZE: BlockSize = 64;
//! const DB_SIZE: Identifier = 64;
//! const DATABASE: [[u8; BLOCK_SIZE as usize]; DB_SIZE as usize] =
//! [[0; BLOCK_SIZE as usize]; DB_SIZE as usize];
//!
//! // Initialize other relevant parameters.
//! let mut rng = OsRng;
//! let mut addresses: [(Identifier, TreeIndex); DB_SIZE as usize] =  
//! [(Identifier::MAX, 0); DB_SIZE as usize];
//! let is_encrypted = rng.gen_bool(0.5);;
//!
//! // Initialize a Path OSAM+ to store 64 blocks of 64 bytes each.
//! let mut osam_plus = PathOsamPlus::<
//!     BlockValue<BLOCK_SIZE>,
//!     DEFAULT_BLOCKS_PER_BUCKET,
//!     DEFAULT_PATH_COUNT,
//!     >::new(DB_SIZE, DEFAULT_STASH_OVERFLOW_SIZE, is_encrypted)?;
//!
//! // Read a database (here, an array of byte arrays) into Path OSAM+.
//! for (i, bytes) in DATABASE.iter().enumerate() {
//!     let address = osam_plus.alloc(&mut rng)?;
//!     addresses[i] = address;
//!     let identifier = address.0;
//!     let position = address.1;
//!     let ordered_evict = rng.gen_bool(0.5);
//!     let _ = osam_plus.write(identifier, position, BlockValue::new(*bytes), ordered_evict, &mut rng)?;
//! }
//!
//! // Now you can safely make secret-dependent accesses to your database.
//! for (i, address) in addresses.iter().enumerate() {
//!     let address = addresses[i];
//!     let identifier = address.0;
//!     let position = address.1;
//!     let ordered_evict = rng.gen_bool(0.5);
//!     let bytes = osam_plus.read(identifier, position, ordered_evict, &mut rng)?.unwrap();
//!     assert_eq!(bytes, BlockValue::new(DATABASE[i]));
//! }
//!
//! # Ok::<(), OsamPlusError>(())
//! ```
//!
//! # Advanced
//!
//! Path OSAM+ can store arbitrary structs implementing `OsamPlusBlock`.
//! We provide implementations of `OsamPlusBlock` for `u8`, `u16`, `u32`, `u64`, `i8`, `i16`, `i32`, `i64`,
//! and `BlockValue<const B: BlockSize>`.
//!
//! The `DefaultOsam` used in the above example should have good performance in most use cases.
//! But the underlying algorithms have several tunable parameters that impact performance.
//! The following example instantiates the same Path OSAM+ struct as above, but using the `PathOsamPlus`
//! interface which exposes these parameters.
//!
//! ```
//! use osam_plus::{
//!     DEFAULT_BLOCKS_PER_BUCKET, DEFAULT_PATH_COUNT, DEFAULT_STASH_OVERFLOW_SIZE,
//!     BlockSize, BlockValue, BucketSize, Identifier, OsamPlus, OsamPlusError, PathOsamPlus, StashSize,
//! };
//! use rand::{rngs::OsRng, Rng};
//!
//! // Declare constants.
//! const BLOCK_SIZE: BlockSize = 64;
//! const DB_SIZE: Identifier = 64;
//! const BUCKET_SIZE: BucketSize = DEFAULT_BLOCKS_PER_BUCKET;
//! const INITIAL_STASH_OVERFLOW_SIZE: StashSize = DEFAULT_STASH_OVERFLOW_SIZE;
//!
//! // Initialize other relevant parameters.
//! let mut rng = OsRng;
//! let is_encrypted = rng.gen_bool(0.5);
//!
//! let mut osam_plus = PathOsamPlus::<
//!     BlockValue<BLOCK_SIZE>,
//!     DEFAULT_BLOCKS_PER_BUCKET,
//!     DEFAULT_PATH_COUNT,
//!     >::new(DB_SIZE, DEFAULT_STASH_OVERFLOW_SIZE, is_encrypted)?;
//! # Ok::<(), OsamPlusError>(())
//! ```
//!
//! See [`PathOsamPlus`] for an explanation of these parameters and their possible settings.

#![warn(clippy::cargo, clippy::doc_markdown, missing_docs, rustdoc::all)]

use bucket::LowLevelBytes;
use rand::{CryptoRng, Rng};
use std::num::TryFromIntError;
use subtle::ConditionallySelectable;
use thiserror::Error;

pub(crate) mod backend;
pub(crate) mod bucket;
pub mod path_osam_plus;
pub(crate) mod stash;
#[cfg(test)]
mod test_utils;
pub(crate) mod utils;

pub use crate::{
    bucket::BlockValue, path_osam_plus::PathOsamPlus, path_osam_plus::DEFAULT_BLOCKS_PER_BUCKET,
    path_osam_plus::DEFAULT_PATH_COUNT, path_osam_plus::DEFAULT_STASH_OVERFLOW_SIZE,
    utils::TreeIndex,
};

/// The numeric type used to specify the size of an OSAM+ block in bytes.
pub type BlockSize = usize;
/// The numeric type used to assign a unique identifier to a block.
pub type Identifier = u64;
/// The numeric type used to specify the size of an OSAM+ bucket in blocks.
pub type BucketSize = usize;
/// The numeric type used to specify the number of paths an OSAM+ can evict simultaneously.
pub type PathCount = usize;
/// Numeric type used to represent the size of a Path OSAM+ stash in blocks.
pub type StashSize = u64;
/// Numeric type used to represent the evict counter in Path OSAM+.
pub type CounterSize = u64;

/// A "trait alias" for OSAM+ blocks: the values read and written by Path OSAM+s.
pub trait OsamPlusBlock:
    Copy + Clone + std::fmt::Debug + Default + PartialEq + ConditionallySelectable + LowLevelBytes
{
}

impl OsamPlusBlock for u8 {}
impl OsamPlusBlock for u16 {}
impl OsamPlusBlock for u32 {}
impl OsamPlusBlock for u64 {}
impl OsamPlusBlock for i8 {}
impl OsamPlusBlock for i16 {}
impl OsamPlusBlock for i32 {}
impl OsamPlusBlock for i64 {}

/// A list of error types which are produced during OSAM+ protocol execution.
#[derive(Error, Debug)]
pub enum OsamPlusError {
    /// Errors arising from conversions between integer types.
    #[error("Arithmetic error encountered.")]
    IntegerConversionError(#[from] TryFromIntError),
    /// Errors arising from invalid parameters or configuration.
    #[error("Invalid configuration. {parameter_name} cannot have value {parameter_value}.")]
    InvalidConfigurationError {
        /// The misconfigured parameter.
        parameter_name: String,
        /// Its invalid value.
        parameter_value: String,
    },
}

/// Represents an oblivious SAM+ (OSAM+) mapping identifiers of type `Identifier`
/// and position of type `TreeIndex` to values of type `V: OsamPlusBlock`.
pub trait OsamPlus
where
    Self: Sized,
{
    /// The type of elements stored in the OSAM+.
    type V: OsamPlusBlock;

    /// Returns the capacity in blocks of this OSAM+.
    fn block_capacity(&self) -> usize;

    /// Allocates a valid `Identifier` and random `TreeIndex` to be used for reading and writing
    fn alloc<R: Rng + CryptoRng>(
        &mut self,
        rng: &mut R,
    ) -> Result<(Identifier, TreeIndex), OsamPlusError>;

    /// Obliviously writes the value stored `identifier` and `position`. Evicts blocks to server.
    fn write<R: Rng + CryptoRng>(
        &mut self,
        identifier: Identifier,
        position: TreeIndex,
        value: Self::V,
        ordered_evict: bool,
        rng: &mut R,
    ) -> Result<(), OsamPlusError>;

    /// Obliviously reads the value stored at `index`.
    fn read<R: Rng + CryptoRng>(
        &mut self,
        identifier: Identifier,
        position: TreeIndex,
        ordered_evict: bool,
        rng: &mut R,
    ) -> Result<Option<Self::V>, OsamPlusError>;
}
